@host = http://localhost:3000

#################
#################
#################
################# API logística
GET {{host}}/api/pedidos/operario
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxLCJ1c2VyX3JvbCI6MSwiaWF0IjoxNjg1OTc2MjM1fQ.0QhbMCkYWFH8npVmZMV6Bq_infVRTFo2QHoY_fzXy3U

###
GET {{host}}/api/pedidos/encargado
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjo0LCJyb2xfaWQiOjIsImV4cF9hdCI6MTY4OTM1NjEzMSwiaWF0IjoxNjg2NzY0MTMxfQ.FtNTFuvUaggtymGMgKYrN_DEMHdduDZvZF2dgLsJGB0

###
GET {{host}}/api/pedidos/operario/7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxLCJ1c2VyX3JvbCI6MSwiaWF0IjoxNjg1OTc2MjM1fQ.0QhbMCkYWFH8npVmZMV6Bq_infVRTFo2QHoY_fzXy3U


###
PUT {{host}}/api/pedidos/operario/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxLCJ1c2VyX3JvbCI6MSwiaWF0IjoxNjg1OTc2MjM1fQ.0QhbMCkYWFH8npVmZMV6Bq_infVRTFo2QHoY_fzXy3U


###
POST {{host}}/api/usuarios/login
Content-Type: application/json

{
    "email": "bromero@gmail.com",
    "password": "bromero1234"
}

###
GET {{host}}/api/usuarios
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjo2LCJleHBfYXQiOjE2ODg1OTAxMDcsImlhdCI6MTY4NTk5ODEwN30.qLRF6xRe5UY3qynj1unGB4GKWudLLTzOQY6uqlmUYAg

###
GET {{host}}/api/usuarios/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjo2LCJleHBfYXQiOjE2ODg1OTAxMDcsImlhdCI6MTY4NTk5ODEwN30.qLRF6xRe5UY3qynj1unGB4GKWudLLTzOQY6uqlmUYAg

###
PUT {{host}}/api/usuarios/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjo2LCJleHBfYXQiOjE2ODg1OTAxMDcsImlhdCI6MTY4NTk5ODEwN30.qLRF6xRe5UY3qynj1unGB4GKWudLLTzOQY6uqlmUYAg
Content-Type: application/json

{
    "nombre": "Berto",
    "apellido": "Romero",
    "rol": "encargado"
}

###
POST {{host}}/api/usuarios
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjo2LCJyb2xfaWQiOjMsImV4cF9hdCI6MTY4OTEwMDk0NSwiaWF0IjoxNjg2NTA4OTQ1fQ.CeC2fPDng26cfmfVg9LVuTYuKvlARdrBtzzjo0x4lKI
Content-Type: application/json

{
    "nombre": "Ernesto",
    "apellido": "Sevilla",
    "email": "esevilla@gmail.com",
    "password":"esevilla1234",
    "rol": "operario"
}
###
GET {{host}}/api/pedidos/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoyLCJleHBfYXQiOjE2ODg4ODk1MDgsImlhdCI6MTY4NjI5NzUwOH0.4hGgq8cljJh96b7puHI_0sOtJaXwCWv8F8nhqCeSQxo


###
POST {{host}}/api/almacenes
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoyLCJleHBfYXQiOjE2ODg4ODk1MDgsImlhdCI6MTY4NjI5NzUwOH0.4hGgq8cljJh96b7puHI_0sOtJaXwCWv8F8nhqCeSQxo
Content-Type: application/json

{
    "nombre": "De la Fuente",
    "responsable_id": 4,
    "direccion": "C/Fuente 123",
    "ciudad": "Catarroja",
    "codigo_postal": 46470
}

###
GET {{host}}/api/almacenes/Las Rosas
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjo2LCJleHBfYXQiOjE2ODg1OTAxMDcsImlhdCI6MTY4NTk5ODEwN30.qLRF6xRe5UY3qynj1unGB4GKWudLLTzOQY6uqlmUYAg

###
GET {{host}}/api/almacenes/jefe
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjo2LCJleHBfYXQiOjE2ODg1OTAxMDcsImlhdCI6MTY4NTk5ODEwN30.qLRF6xRe5UY3qynj1unGB4GKWudLLTzOQY6uqlmUYAg


###
PUT {{host}}/api/almacenes/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoyLCJleHBfYXQiOjE2ODg4ODk1MDgsImlhdCI6MTY4NjI5NzUwOH0.4hGgq8cljJh96b7puHI_0sOtJaXwCWv8F8nhqCeSQxo
Content-Type: application/json

{
    "nombre": "De la",
    "responsable_id": 4,
    "direccion": "C/ 123",
    "ciudad": "Cat",
    "codigo_postal": 46470
}

###
PUT {{host}}/api/pedidos/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxLCJyb2xfaWQiOjEsImV4cF9hdCI6MTY4ODk5MDA5MCwiaWF0IjoxNjg2Mzk4MDkwfQ.9Iue8GsB2mY5xbfb18sOXy_TR8q5lN9OFSp5MsQHO18
//Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoyLCJleHBfYXQiOjE2ODg4ODk1MDgsImlhdCI6MTY4NjI5NzUwOH0.4hGgq8cljJh96b7puHI_0sOtJaXwCWv8F8nhqCeSQxo
Content-Type: application/json

{
    "fecha_salida": "2023-08-31",
    "almacen_origen": "Fuente del Jarro",
    "almacen_destino": "Las Rosas",
    "matricula": "5678-DEF",
    "detalles_carga": "3 bolis azules"
}

###
POST {{host}}/api/pedidos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxLCJyb2xfaWQiOjEsImV4cF9hdCI6MTY4ODk5MDA5MCwiaWF0IjoxNjg2Mzk4MDkwfQ.9Iue8GsB2mY5xbfb18sOXy_TR8q5lN9OFSp5MsQHO18
Content-Type: application/json

{
    "fecha_salida": "2023-09-01",
    "almacen_origen": "ColeVega",
    "almacen_destino": "Fuente del Jarro",
    "matricula": "1234-ABC",
    "detalles_carga": "2 bolis verdes"
}

###
PUT {{host}}/api/pedidos/operario/enviorevision/5
//Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxLCJyb2xfaWQiOjEsImV4cF9hdCI6MTY4ODk5MDA5MCwiaWF0IjoxNjg2Mzk4MDkwfQ.9Iue8GsB2mY5xbfb18sOXy_TR8q5lN9OFSp5MsQHO18
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoyLCJyb2xfaWQiOjEsImV4cF9hdCI6MTY4OTMyNTQyMSwiaWF0IjoxNjg2NzMzNDIxfQ.BV3N1zsAA2KY6z3_-tI9qYk-60aY2ZCUzvl_IFPU2cs

###
PUT {{host}}/api/pedidos/operario/cerrar/11
//Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxLCJyb2xfaWQiOjEsImV4cF9hdCI6MTY4ODk5MDA5MCwiaWF0IjoxNjg2Mzk4MDkwfQ.9Iue8GsB2mY5xbfb18sOXy_TR8q5lN9OFSp5MsQHO18
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoyLCJyb2xfaWQiOjEsImV4cF9hdCI6MTY4OTMyNTQyMSwiaWF0IjoxNjg2NzMzNDIxfQ.BV3N1zsAA2KY6z3_-tI9qYk-60aY2ZCUzvl_IFPU2cs

###
PUT {{host}}/api/pedidos/encargado/aprobar/9
//Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjo1LCJyb2xfaWQiOjIsImV4cF9hdCI6MTY4OTM0MjMxMiwiaWF0IjoxNjg2NzUwMzEyfQ.Bu-Jl41Mz2OynXbM4cqrEfnEKFAslzJD-uHHYNvI5hA
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjo0LCJyb2xfaWQiOjIsImV4cF9hdCI6MTY4OTM0MjU1NSwiaWF0IjoxNjg2NzUwNTU1fQ.PJN61cXjImC0N3ORcGUogzsABpvFxelaGbJv1xRjZEE

###
PUT {{host}}/api/pedidos/encargado/denegar/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjo0LCJyb2xfaWQiOjIsImV4cF9hdCI6MTY4OTM0NDI5NiwiaWF0IjoxNjg2NzUyMjk2fQ.dgNM2av57MbKcfBzZBEH2EQmGMAoC95anD8ZPkcGuSY
//Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxMSwicm9sX2lkIjoyLCJleHBfYXQiOjE2ODkzNDM3NjUsImlhdCI6MTY4Njc1MTc2NX0.fAh6PoU3Lx_Y8Qxf8jEbDy99jziGz84fWZGWN5Yt34o
Content-Type: application/json

{
    "comentario_error": "Faltan 3 bolis azules"
}